SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS pr_activity;
DROP TABLE IF EXISTS pr_hcd;
DROP TABLE IF EXISTS pr_workload;
DROP TABLE IF EXISTS pr_ttbl;
DROP TABLE IF EXISTS pr_staff;
DROP TABLE IF EXISTS pr_staff_department;
DROP TABLE IF EXISTS pr_class_section;
DROP TABLE IF EXISTS pr_class;
DROP TABLE IF EXISTS principal_report;
DROP TABLE IF EXISTS staff;
DROP TABLE IF EXISTS staff_status;
DROP TABLE IF EXISTS designation;
DROP TABLE IF EXISTS department;
DROP TABLE IF EXISTS session;
DROP TABLE IF EXISTS campus;
DROP TABLE IF EXISTS city;
DROP TABLE IF EXISTS class_section;
DROP TABLE IF EXISTS class;
DROP TABLE IF EXISTS __drizzle_migrations;

SET FOREIGN_KEY_CHECKS = 1;
